# Generated by Django 5.0.2 on 2024-02-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
